## HouseHolder

In [2]:
#https://elearn.mtsu.edu/d2l/le/content/7975450/viewContent/68711883/View

import numpy as np
from numpy import linalg as LA

b = np.array([[3, 4, -4],[5, -16, 2],[13, -3, -7]])
b

array([[  3,   4,  -4],
       [  5, -16,   2],
       [ 13,  -3,  -7]])

In [3]:
z = []
for item in b:
    z.append(item[0])
z = np.array(z).reshape(3,1)
z

array([[ 3],
       [ 5],
       [13]])

In [4]:
e1 = [0] * 3
e1[0] = 1
e1 = np.array(e1).reshape(3,1)
e1

array([[1],
       [0],
       [0]])

In [5]:
v = [None] * 3
for i in range(0, len(v)):
    v[i] = z[i] - LA.norm(z) * e1[i]
v = np.array(v).reshape(3,1)
v

array([[-11.24780685],
       [  5.        ],
       [ 13.        ]])

In [6]:
np.transpose(v)

array([[-11.24780685,   5.        ,  13.        ]])

In [7]:
vvt = np.matmul(v,np.transpose(v))
vvt

array([[ 126.51315891,  -56.23903424, -146.22148903],
       [ -56.23903424,   25.        ,   65.        ],
       [-146.22148903,   65.        ,  169.        ]])

In [8]:
vtv = np.matmul(np.transpose(v),v)
vtv

array([[320.51315891]])

In [9]:
h = np.identity(3) - 2 * vvt / vtv
h

array([[ 0.21055872,  0.3509312 ,  0.91242113],
       [ 0.3509312 ,  0.84400016, -0.40559957],
       [ 0.91242113, -0.40559957, -0.05455889]])

In [10]:
np.matmul(h,b)

array([[ 1.42478068e+01, -7.50992775e+00, -6.52732038e+00],
       [ 1.66533454e-16, -1.08834791e+01,  3.12347252e+00],
       [ 1.99840144e-15,  1.03029543e+01, -4.07897145e+00]])

## QR Iteration

In [11]:
#https://elearn.mtsu.edu/d2l/le/content/7975450/viewContent/68711883/View

a = np.array([[3, 2],[-4, 1]])
a

array([[ 3,  2],
       [-4,  1]])

In [12]:
d,v = LA.eig(a)

In [13]:
v

array([[-0.20412415-0.54006172j, -0.20412415+0.54006172j],
       [ 0.81649658+0.j        ,  0.81649658-0.j        ]])

In [14]:
d

array([2.+2.64575131j, 2.-2.64575131j])

In [15]:
d_v = [[0, 0],[0,0]]
for i in range(0, len(d)):
    d_v[i][i] = d[i]
d_v = np.array(d_v)
d_v

array([[2.+2.64575131j, 0.+0.j        ],
       [0.+0.j        , 2.-2.64575131j]])

In [17]:
d_v[0][1] == 0

True

In [18]:
np.matmul(a,v)

array([[1.02062073-1.62018517j, 1.02062073+1.62018517j],
       [1.63299316+2.1602469j , 1.63299316-2.1602469j ]])

In [19]:
testing_v = np.matmul(v,d_v)
np.matmul(v,d_v)

array([[1.02062073-1.62018517j, 1.02062073+1.62018517j],
       [1.63299316+2.1602469j , 1.63299316-2.1602469j ]])

In [20]:
testing_v[0][1] == 0

False

#### Example2

In [21]:
c = np.array([[20, 3],[12, 5]])
c

array([[20,  3],
       [12,  5]])

In [22]:
d, v = LA.eig(c)

In [23]:
v

array([[ 0.81863069, -0.17275355],
       [ 0.57432028,  0.98496508]])

In [24]:
d

array([22.10468636,  2.89531364])

In [25]:
d_v = [[0, 0],[0,0]]
for i in range(0, len(d)):
    d_v[i][i] = d[i]
d_v = np.array(d_v)
d_v

array([[22.10468636,  0.        ],
       [ 0.        ,  2.89531364]])

In [26]:
np.matmul(c,v)

array([[18.09557472, -0.5001757 ],
       [12.69516974,  2.85178284]])

In [27]:
np.matmul(v,d_v)

array([[18.09557472, -0.5001757 ],
       [12.69516974,  2.85178284]])

In [30]:
np.matmul(c,d_v)

array([[442.09372712,   8.68594093],
       [265.25623627,  14.47656822]])