In [51]:
import numpy as np
from numpy import linalg as LA

def column_convertor(x):
    x.shape = (1, x.shape[0])
    return x

def householder_transformation(v):
    size_of_v = v.shape[1]
    e1 = np.zeros_like(v)             #Makes an array the same dim as v with zeros
    e1[0, 0] = 1                      #Changes the first value to 1
    vector = LA.norm(v) * e1
    if v[0, 0] < 0:
        vector = - vector
    u = (v + vector).astype(np.float32)
    H = np.identity(size_of_v) - ((2 * np.matmul(np.transpose(u), u)) / np.matmul(u, np.transpose(u)))
    return H

def qr_factorization(q, r, iter, n):  #Math stuff. Self note: DO NOT CHANGE!!!
    v = column_convertor(r[iter:, iter])
    Hbar = householder_transformation(v)
    H = np.identity(n)
    H[iter:, iter:] = Hbar
    r = np.matmul(H, r)
    q = np.matmul(q, H)
    return q, r

def internalTest(Q,R,A):
    internalTest = input("Run internal test?:(Y/N) \n")  #Test against the linalg qr function if needed
    while True:
        if internalTest == "Y":
            print("Q * R = ")           #Values given from homebrew function
            print(np.matmul(Q,R))
            print("\n")
            print("Actual Q * R = ")    #Values given from actual function
            act_Q, act_R = np.linalg.qr(A)
            print(np.matmul(act_Q,act_R))
            break
        elif internalTest == "N":       #No testing required
            print("Thank you")
            break
        else:                           #Remove some user error
            internalTest = input("Invalid input. Try again:")

def myMatrix():
    ManualOrRandom = input("Would you like to manually enter a matrix or create a random matrix?:(Manual/Random) \n")
    while True:
        if ManualOrRandom == 'Manual':   #Ask if specific matrix needed to to generate a random
            break
        elif ManualOrRandom == 'Random':
            break
        else:                           #Remove some user error
            ManualOrRandom = input("Invalid input. Please try again:(Manual/Random) \n")
    
    if ManualOrRandom == 'Random':      #Ask for dimensions if generating a random
        n, m = list(map(int, input("Write size of the matrix in comma separated format\n").split(",")))
        A = np.random.rand(n,m)
        print('Random matrix: \n', A)
        
    else:                               #Manually enter a matrix
        n, m = list(map(int, input("Write size of the matrix in comma separated format\n").split(",")))
        values = input("Please enter values with spaces between each number:").split(" ")
        for i in range(0, len(values)):
            values[i] = int(values[i])
        A = np.reshape(values, (n,m))
        print('Given matrix: \n', A)
    
    true_min = min(n, m)                #Determine the number of iterations needed and used for trimming
    true_max = max(n, m)                #Used later for trimming
    
    Q = np.identity(n)
    R = A.astype(np.float32)
    
    for i in range(true_min):
        Q, R = qr_factorization(Q, R, i, n)
    
    if n == m:                          #Trim the matrices if they are too long
        R = R[:true_min, :true_min]
    elif n > m:
        Q = np.delete(Q, -1, axis=1)
        R = R[:true_min, :true_min]
    else:
        R = R[:true_min, :true_max]
    
    R = np.round(R, decimals=6)         #Clean up R for decimals
    
    Q = np.round(Q, decimals=6)         #Clean up Q for decimals
    
    
    
    
    
    print('R =')
    print(R, '\n')
    print('Q =')
    print(Q)
    
    internalTest(Q,R,A)                 #Send user to testing

myMatrix()

Would you like to manually enter a matrix or create a random matrix?:(Manual/Random) 
Random
Write size of the matrix in comma separated format
3,2
Random matrix: 
 [[0.66045042 0.62403869]
 [0.79638901 0.10817027]
 [0.04140732 0.70666569]]
R =
[[-1.035444 -0.509495]
 [-0.        0.800573]] 

Q =
[[-0.637843  0.373559]
 [-0.769128 -0.354367]
 [-0.03999   0.85725 ]]
Run internal test?:(Y/N) 
N
Thank you


In [48]:
myMatrix()

Would you like to manually enter a matrix or create a random matrix?:(Manual/Random) 
Manual
Write size of the matrix in comma separated format
3,3
Please enter values with spaces between each number:1 2 3 4 5 6 7 8 9
Given matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
R =
[[ -8.124039  -9.601137 -11.078235]
 [ -0.         0.904534   1.809068]
 [ -0.        -0.         0.      ]] 

Q =
[[-0.123092  0.904534 -0.408248]
 [-0.492366  0.301511  0.816497]
 [-0.86164  -0.301511 -0.408248]]
Run internal test?:(Y/N) 
Y
Q * R = 
[[1.00000421 2.00000491 3.00000562]
 [4.00000059 5.00000037 6.00000016]
 [6.99999696 7.99999673 8.9999965 ]]


Actual Q * R = 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [49]:
myMatrix()

Would you like to manually enter a matrix or create a random matrix?:(Manual/Random) 
Random
Write size of the matrix in comma separated format
3,2
Random matrix: 
 [[0.70014647 0.19271159]
 [0.50916479 0.17803647]
 [0.81871552 0.56789046]]
R =
[[-1.191532 -0.57952 ]
 [ 0.        0.235565]] 

Q =
[[-0.587602 -0.627495]
 [-0.427319 -0.295476]
 [-0.687111  0.720378]]
Run internal test?:(Y/N) 
Y
Q * R = 
[[0.70014659 0.19271125]
 [0.50916426 0.1780361 ]
 [0.81871474 0.56789041]]


Actual Q * R = 
[[0.70014647 0.19271159]
 [0.50916479 0.17803647]
 [0.81871552 0.56789046]]


In [50]:
myMatrix()

Would you like to manually enter a matrix or create a random matrix?:(Manual/Random) 
Random
Write size of the matrix in comma separated format
2,3
Random matrix: 
 [[0.69865012 0.49026516 0.17041782]
 [0.21618058 0.4833902  0.80382657]]
R =
[[-0.731332 -0.611246 -0.400412]
 [-0.       -0.316867 -0.71753 ]] 

Q =
[[-0.955312  0.295599]
 [-0.295599 -0.955312]]
Run internal test?:(Y/N) 
Y
Q * R = 
[[0.69865024 0.49026507 0.17041724]
 [0.21618101 0.48339055 0.80382641]]


Actual Q * R = 
[[0.69865012 0.49026516 0.17041782]
 [0.21618058 0.4833902  0.80382657]]
